name: Web Build Release
on:
  push:
    branches:
      - v3.dev
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Fetching Latest Codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Flutter Set-Up
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get Dependency
        run: flutter pub get && flutter pub upgrade

      - name: Enable Web Support
        run: flutter config --enable-web

      - name: Build Web
        run: flutter build web --release

      - name: Checkout Repo in build-branch folder
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: build-branch

      - name: Switching to build.v3 branch
        working-directory: build-branch
        run: git checkout -B build.v3

      - name: Sync build output to target branch
        run: |
          rsync -av --delete-after build/web/ build-branch/

      - name: Commit and push changes
        working-directory: build-branch
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          # Authenticate using GITHUB_TOKEN
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          if ! git diff-index --quiet HEAD --; then 
            git commit -a -u -m "latest v3 web release [skip ci]"
            git push origin build.v3
          else
            echo "No changes to commit"
          fi